### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by techniplex** [kakwa/ldapcherry#29]
I have attempted to install in ubuntu 18.04LTS and within a docker image of 16.04 but keep running into errors trying to start LDAPCHERRY although it seems everything installed. I am probably missing a prerequisite. Is there a running docker image out there? Here is the error I get when attempting to start:

root@5ee084e76c6b:/ldapcherry# ldapcherryd -c /etc/ldapcherry/ldapcherry.ini -D
Traceback (most recent call last):
  File "/usr/local/bin/ldapcherryd", line 11, in <module>
    load_entry_point('ldapcherry==1.1.1', 'console_scripts', 'ldapcherryd')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2792, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'ldapcherryd') not found
root@5ee084e76c6b:/ldapcherry#

**Comment by smacz42** [comment]
Take a look at https://gitlab.com/smacz/docker-ldapcherry/blob/andrewcz-homelab-179/Dockerfile

FWIW, it takes a bit of finagling to set up.
