### ISSUE TITLE
error when building with python3

### ISSUE THREAD

**Issue by wrosenauer** [kakwa/ldapcherry#37]
Is this an error or is python 3 not supported?

[   56s] + /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
[   57s] Traceback (most recent call last):
[   57s]   File "setup.py", line 44, in <module>
[   57s]     description = f.read()
[   57s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[   57s]     return codecs.ascii_decode(input, self.errors)[0]
[   57s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1152: ordinal not in range(128)

**Comment by wrosenauer** [comment]
Caused by my build environment and found a workaround
