### ISSUE TITLE
DATAROOTDIR env not working

### ISSUE THREAD

**Issue by chestarss** [kakwa/ldapcherry#56]
➜  ldapcherry DATAROOTDIR=/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/share/ ldapcherryd -c /etc/ldapcherry/ldapcherry.ini -D
[23/Oct/2019:10:16:14]  loading templates from dir '/usr/share/ldapcherry/templates/'
[23/Oct/2019:10:16:14]  uncaught exception: [Cant locate template for uri 'index.tmpl']
[23/Oct/2019:10:16:14]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Mako-1.1.0-py3.7.egg/mako/lookup.py", line 249, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'index.tmpl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ldapcherry-1.1.1-py3.7.egg/ldapcherry/__init__.py", line 417, in reload
    self._load_templates(config)
  File "/usr/local/lib/python3.7/site-packages/ldapcherry-1.1.1-py3.7.egg/ldapcherry/__init__.py", line 393, in _load_templates
    self.temp[t] = self.temp_lookup.get_template(t)
  File "/usr/local/lib/python3.7/site-packages/Mako-1.1.0-py3.7.egg/mako/lookup.py", line 263, in get_template
    "Cant locate template for uri %r" % uri
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'index.tmpl'
[23/Oct/2019:10:16:14]  application failed to start

**Comment by chestarss** [comment]
[resources]
# templates directory
templates.dir = '/usr/share/ldapcherry/templates/'

closed, in config file can specifi
