### ISSUE TITLE
uncaught exception: ['value']

### ISSUE THREAD

**Issue by dakolta** [kakwa/ldapcherry#67]
had to set auth to none to be able to edit a user to add as admin, when I try to modify a user I get the following:
uncaught exception: ['value']
Python Exception:
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/ldapcherry-1.1.1-py3.8.egg/ldapcherry/exceptions.py", line 229, in ret
    return func(self, *args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/ldapcherry-1.1.1-py3.8.egg/ldapcherry/__init__.py", line 1140, in modify
    form = self.temp['form.tmpl'].render(

  File "/usr/local/lib/python3.8/dist-packages/Mako-1.1.3-py3.8.egg/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)

  File "/usr/local/lib/python3.8/dist-packages/Mako-1.1.3-py3.8.egg/mako/runtime.py", line 878, in _render
    _render_context(

  File "/usr/local/lib/python3.8/dist-packages/Mako-1.1.3-py3.8.egg/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

  File "/usr/local/lib/python3.8/dist-packages/Mako-1.1.3-py3.8.egg/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)

  File "form_tmpl", line 47, in render_body

  File "form_tmpl", line 23, in form_col

  File "form_tmpl", line 225, in render_form_col

KeyError: 'value'

**Comment by dakolta** [comment]
Found out the problem is if I set the type to fix I get this error.
How else can I set attributes to read only?
